---
- name: Service Update — Update images and restart services
  hosts: ibl_servers
  become: true

  vars:
    python_version: "3.11.8"
    venv_name: "ibl-cli-ops"
    ibl_root: /ibl
    repo_dir: "/home/{{ ansible_user }}/ibl-cli-ops"
    pyenv_root: "/home/{{ ansible_user }}/.pyenv"
    bashrc_path: "/home/{{ ansible_user }}/.bashrc"

  roles:
    - ibl_cli_ops
    - ibl_service_update
