---
- name: Configure IBL platform
  become: false
  shell: |
    export PYENV_ROOT="{{ pyenv_root }}"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"; eval "$(pyenv virtualenv-init -)"
    pyenv activate "{{ venv_name }}"

    ibl config save --set IBL_EDX.VERSION='{{ edx_version }}'
    ibl config save --set BASE_DOMAIN='{{ base_domain }}'
    ibl global-proxy launch-without-security
    ibl config save --set ENVIRONMENT_CONFIG='{{ env_config }}'
  args:
    executable: /bin/bash
  environment:
    HOME: "/home/{{ ansible_user }}"
