---
- name: Seed DM flows
  become: false
  shell: |
    cd {{ ibl_root }}/app/ibl-dm/ibl-dm-pro/ && docker compose exec -T web ./manage.py seed_flows
  args:
    executable: /bin/bash
  environment:
    HOME: "/home/{{ ansible_user }}"

- name: Seed LLM registry
  become: false
  shell: |
    cd {{ ibl_root }}/app/ibl-dm/ibl-dm-pro/ && docker compose exec -T web ./manage.py seed_llm_registry
  args:
    executable: /bin/bash
  environment:
    HOME: "/home/{{ ansible_user }}"

- name: Seed base mentors
  become: false
  shell: |
    cd {{ ibl_root }}/app/ibl-dm/ibl-dm-pro/ && docker compose exec -T web ./manage.py seed_base_mentors
  args:
    executable: /bin/bash
  environment:
    HOME: "/home/{{ ansible_user }}"

- name: Seed RBAC data
  become: false
  shell: |
    cd {{ ibl_root }}/app/ibl-dm/ibl-dm-pro/ && docker compose exec -T web ./manage.py seed_rbac_data
  args:
    executable: /bin/bash
  environment:
    HOME: "/home/{{ ansible_user }}"

- name: Setup TimescaleDB views
  become: false
  shell: |
    cd {{ ibl_root }}/app/ibl-dm/ibl-dm-pro/ && echo "y" | docker compose exec -T web ./manage.py setup_timescale_views --full-setup
  args:
    executable: /bin/bash
  environment:
    HOME: "/home/{{ ansible_user }}"
  ignore_errors: true

- name: Recreate analytics views
  become: false
  shell: |
    cd {{ ibl_root }}/app/ibl-dm/ibl-dm-pro/ && docker compose exec -T web ./manage.py refresh_analytics_views --recreate
  args:
    executable: /bin/bash
  environment:
    HOME: "/home/{{ ansible_user }}"

- name: Refresh analytics views
  become: false
  shell: |
    cd {{ ibl_root }}/app/ibl-dm/ibl-dm-pro/ && docker compose exec -T web ./manage.py refresh_analytics_views
  args:
    executable: /bin/bash
  environment:
    HOME: "/home/{{ ansible_user }}"
