---
- name: Save config and reload proxy
  become: false
  shell: |
    export PYENV_ROOT="{{ pyenv_root }}"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"; eval "$(pyenv virtualenv-init -)"
    pyenv activate "{{ venv_name }}"
    ibl config save && \
    ibl global-proxy reload && \
    ibl launch --ibl-oauth --ibl-oidc --ibl-edx-manager && \
    ibl dm auth-setup
  args:
    executable: /bin/bash
    chdir: "{{ repo_dir }}"
  environment:
    HOME: "/home/{{ ansible_user }}"
    IBL_ROOT: "{{ ibl_root }}/"

- name: Sync edX with DM
  become: false
  shell: |
    export PYENV_ROOT="{{ pyenv_root }}"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"; eval "$(pyenv virtualenv-init -)"
    pyenv activate "{{ venv_name }}"
    ibl edx sync-with-manager --users
  args:
    executable: /bin/bash
    chdir: "{{ repo_dir }}"
  environment:
    HOME: "/home/{{ ansible_user }}"
    IBL_ROOT: "{{ ibl_root }}/"
